# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-20 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20, verbose_name='类别名称')),
                ('type_logo', models.CharField(max_length=20, verbose_name='类别标志')),
                ('type_image', models.ImageField(upload_to='type/', verbose_name='类别图片')),
            ],
            options={
                'verbose_name': '商品类别表',
                'verbose_name_plural': '商品类别',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='GoodsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(verbose_name='商品描述')),
                ('desc_detail', models.TextField(verbose_name='商品详情')),
            ],
            options={
                'verbose_name': '商品描述表',
                'verbose_name_plural': '商品描述',
                'db_table': 'goodsdetail',
            },
        ),
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=25, verbose_name='商品名称')),
                ('goods_img', models.ImageField(upload_to='goods/', verbose_name='商品图片')),
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='商品价格')),
                ('goods_unit', models.CharField(choices=[('a', 'kg/元'), ('b', '斤/元'), ('c', '个/元')], max_length=10, verbose_name='单位')),
                ('goods_repertory', models.IntegerField(verbose_name='库存')),
                ('goods_status', models.CharField(choices=[('aa', '上架'), ('bb', '下架')], max_length=10, verbose_name='状态')),
                ('goods_click_rate', models.IntegerField(default=0, verbose_name='点击量')),
                ('goods_shelf_time', models.DateTimeField(verbose_name='上架时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Category', verbose_name='商品类别')),
            ],
            options={
                'verbose_name': '商品信息表',
                'verbose_name_plural': '商品信息',
                'db_table': 'goodsinfo',
            },
        ),
        migrations.CreateModel(
            name='Recently',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsInfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Users')),
            ],
            options={
                'db_table': 'recently',
            },
        ),
        migrations.CreateModel(
            name='RotationChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_c_img', models.ImageField(upload_to='rotationchart/', verbose_name='首页轮播图')),
            ],
            options={
                'verbose_name': '首页轮播图表',
                'verbose_name_plural': '首页轮播图',
                'db_table': 'rotationchart',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_img', models.ImageField(upload_to='sales/', verbose_name='热销商品')),
            ],
            options={
                'verbose_name': '热销图片表',
                'verbose_name_plural': '热销图片',
                'db_table': 'Sales',
            },
        ),
        migrations.AddField(
            model_name='goodsdetail',
            name='goods',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsInfo', verbose_name='商品'),
        ),
    ]
