# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-20 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_method', models.IntegerField(default=1, verbose_name='支付方式')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品总计')),
                ('total_count', models.IntegerField(default=1, verbose_name='商品的总数量')),
                ('transit_price', models.DecimalField(decimal_places=2, default=10.0, max_digits=10, verbose_name='商品运费')),
                ('order_status', models.IntegerField(default=1)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('trade_no', models.CharField(default='', max_length=128, verbose_name='支付编号')),
                ('order_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Address', verbose_name='收货地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Users', verbose_name='用户')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('count', models.IntegerField()),
                ('comment', models.TextField(default='', verbose_name='商品评论')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsInfo')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
            options={
                'db_table': 'orderdetail',
            },
        ),
    ]
