# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-22 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_method',
            field=models.IntegerField(default=3, verbose_name='支付方式'),
        ),
    ]
