# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-22 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190222_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '订单表', 'verbose_name_plural': '订单'},
        ),
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'verbose_name': '订单详情表', 'verbose_name_plural': '订单详情'},
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now=True, verbose_name='购买时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(default=1, verbose_name='支付方式'),
        ),
    ]
