# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-26 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190222_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='comment_status',
            field=models.IntegerField(default=0, verbose_name='是否评论'),
        ),
    ]
